language: node_js
sudo: required
node_js:
- '8.10'
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn install
  - source .ci/detect-changed-services.sh && detect_changed_services && echo $changed_services
env:
  global:
    - ES_VERSION=6.0.0
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
 
stages:
  - test
  - name: staging-deploy
    if: branch = master AND type = push
  - name: prod-deploy
    if: branch = release AND type = push

jobs:
  include:
    - stage: test
      script: ./.ci/test.sh     
    
    - stage: staging-deploy
      script: ./.ci/staging-deploy.sh
      
    - stage: prod-deploy
      script: ./.ci/prod-deploy.sh 
      
cache:
  yarn: true
  directories:
  - "$(npm config get prefix)/lib/node_modules"
  - node_modules
  - events/node_modules
  - api/node_modules
  - private/node_modules
  - extensions/node_modules
  - template-marketplace/node_modules
  - lists-microservice/node_modules
  - emails-microservice/node_modules
  - campaigns-microservice/node_modules
  - events-router/node_modules
