service: my-service-name

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-aws-alerts

custom:
  defaultStage: dev
  currentStage: dev
  resourcesPrefix: ${self:service}-${self:custom.currentStage}
  config: ${file(./config.${self:custom.currentStage}.json)}
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
  serverless-offline:
    babelOptions:
      presets: ["es2015"]
  alerts:
    stages:
      - prod
    topics:
      alarm: 
        topic: ${self:service}-dev-alerts-alarm
        notifications:
          - protocol: email
            endpoint: hi@crecatalyst.com # Change this to your email address

provider:
  name: aws
  runtime: nodejs10.x
  profile: "default"
  region: "us-west-2"
  timeout: 300
  environment:
    REGION: "us-west-2"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

package:
  individually: true

functions:
  hello:
    handler: src/handler.default
    events:
      - http:
          path: version
          method: get

